#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh" # Loads all defined icons

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

FONT="Ubuntu"
ICON_FONT="Monaco Nerd Font"

PADDINGS=3 # All paddings use this value (icon, label, background)

# CPU helper
HELPER=git.felix.helper
killall helper
(cd $CONFIG_DIR/helper && make)
$CONFIG_DIR/helper/helper $HELPER > /dev/null 2>&1 &

# Setting up the general bar appearance of the bar
bar=(
  height=40
  # display=1
  color=$TRANSPARENT
  blur_radius=30
  border_width=0
  border_color=$BAR_BORDER_COLOR
  shadow=on
  position=bottom
  sticky=on
  padding_right=0
  padding_left=0
  y_offset=1
  margin=0
  topmost=window
  corner_radius=5
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  updates=when_shown
  icon.font="$FONT:Regular:12.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Regular:11.0"
  label.color=$LABEL_COLOR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  background.border_width=1
  popup.background.border_width=1
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOR
  popup.background.color=$POPUP_BACKGROUND_COLOR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
  scroll_texts=on
)

sketchybar --default "${defaults[@]}"

# Left
source "$ITEM_DIR/apple.sh"
# 延迟1.5秒再出现space，因为aerospace可能还没初始化完成
sleep 1.5
source "$ITEM_DIR/aerospace.sh"

# Center
source "$ITEM_DIR/media.sh"
source "$ITEM_DIR/front_app.sh"

# Right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --hotload on



# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
echo "sketchybar configuation loaded.."
