#!/usr/bin/env sh
# brew install yabai
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# 全局设置
yabai -m config debug_output                 on
yabai -m config external_bar                 all:0:35
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.50
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5
yabai -m config window_animation_duration    0.00

# 不受影响的窗口
yabai -m rule --add app="^系统设置$" manage=off
yabai -m rule --add app="^访达$" manage=off
yabai -m rule --add app="^微信$" manage=off
yabai -m rule --add app="^企业微信$" manage=off
yabai -m rule --add app="^Mac Mouse Fix$" manage=off
yabai -m rule --add app="^Step Two$" manage=off
yabai -m rule --add app="^日历$" manage=off
yabai -m rule --add app="^Tencent Lemon$" manage=off
yabai -m rule --add app="^网易云音乐$" manage=off
yabai -m rule --add app="^计算器$" manage=off
yabai -m rule --add app="^Clash Verge$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^贝锐向日葵$" manage=off
yabai -m rule --add app="^贝锐蒲公英$" manage=off
yabai -m rule --add app="^花生壳$" manage=off
yabai -m rule --add app="^字体册$" manage=off
yabai -m rule --add app="^Keka$" manage=off
yabai -m rule --add app="^归档实用工具$" manage=off
yabai -m rule --add app="^便笺$" manage=off
yabai -m rule --add app="^uTools$" manage=off
yabai -m rule --add app="^iStat Menus$" manage=off
yabai -m rule --add app="^文本编辑$" manage=off
yabai -m rule --add app="^爱奇艺$" manage=off

# Jetbrains系列APP处理
JB_Apps='^(CLion|PyCharm|IntelliJ IDEA|GoLand|DataGrip$$)$'
yabai -m rule --add app="${JB_Apps}" manage=off
yabai -m rule --add app="${JB_Apps}" title=".*\[.*\].*" manage=on
yabai -m rule --add app="${JB_Apps}" title="^$"  manage=on

# 自动管理Space
yabai -m signal --add event=window_created \
  action="~/.config/yabai/auto_space.sh"
yabai -m signal --add event=window_destroyed \
  action="~/.config/yabai/auto_space.sh"
yabai -m signal --add event=space_changed \
  action="~/.config/yabai/auto_space.sh"

# brew install borders
# border_options=(
# 	style=round
# 	width=2.0
# 	hidpi=on
# 	active_color=0xffe2e2e3
# 	inactive_color=0xff414550
# )
# borders "${border_options[@]}"

echo "yabai configuration loaded.."
