# on-my-zsh
ZSH_THEME="linuxonly"
export ZSH="$HOME/.oh-my-zsh"
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

# Nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Java
export JAVA_HOME="${HOME}/Library/Java/JavaVirtualMachines/corretto-1.8.0_382/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

# Golang
export GOPROXY="https://goproxy.cn"
export GO111MODULE="on"
export GOPRIVATE="gitlab.orayer.com"
export GOINSECURE="gitlab.orayer.com"
export GONOPROXY="gitlab.orayer.com"
export GONOSUMDB="gitlab.orayer.com"
export GOPATH="${HOME}/Public/Library/golang-library"
export GOROOT="${HOME}/Public/Library/golang-sdk/go1.19.10"
export PATH="$GOROOT/bin:$GOPATH/bin:$PATH"


# Alias
alias vim="nvim"
alias vi="nvim"
